# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/calculator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16proto/calculator.proto\"(\n\nRequestAdd\x12\x0c\n\x04num1\x18\x01 \x01(\x03\x12\x0c\n\x04num2\x18\x02 \x01(\x03\"\x1c\n\nResponeAdd\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32+\n\x03\x41\x64\x64\x12$\n\x08\x41\x64\x64ition\x12\x0b.RequestAdd\x1a\x0b.ResponeAddb\x06proto3'
)




_REQUESTADD = _descriptor.Descriptor(
  name='RequestAdd',
  full_name='RequestAdd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='RequestAdd.num1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num2', full_name='RequestAdd.num2', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=66,
)


_RESPONEADD = _descriptor.Descriptor(
  name='ResponeAdd',
  full_name='ResponeAdd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ResponeAdd.result', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['RequestAdd'] = _REQUESTADD
DESCRIPTOR.message_types_by_name['ResponeAdd'] = _RESPONEADD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestAdd = _reflection.GeneratedProtocolMessageType('RequestAdd', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTADD,
  '__module__' : 'proto.calculator_pb2'
  # @@protoc_insertion_point(class_scope:RequestAdd)
  })
_sym_db.RegisterMessage(RequestAdd)

ResponeAdd = _reflection.GeneratedProtocolMessageType('ResponeAdd', (_message.Message,), {
  'DESCRIPTOR' : _RESPONEADD,
  '__module__' : 'proto.calculator_pb2'
  # @@protoc_insertion_point(class_scope:ResponeAdd)
  })
_sym_db.RegisterMessage(ResponeAdd)



_ADD = _descriptor.ServiceDescriptor(
  name='Add',
  full_name='Add',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=98,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='Addition',
    full_name='Add.Addition',
    index=0,
    containing_service=None,
    input_type=_REQUESTADD,
    output_type=_RESPONEADD,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADD)

DESCRIPTOR.services_by_name['Add'] = _ADD

# @@protoc_insertion_point(module_scope)
